### ISSUE TITLE
Define a way to create a batch CID deal using another smart contract or similar

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#12]

**Comment by irenegia** [comment]
when you implement this and close the issue, could you please add a brief description of the design you choose for it?

Thanks!

**Comment by turinglabsorg** [comment]
we decided to move from `ipfs_hash` to a more generic `deal_uri` which can be a single hash, a folder or a string that includes more cids. This will affect the `provider-cli` package since just before accepting the deal should/must check or retrieve the files someway (this is not a function included in cli at the moment).

**Comment by 0xjona** [comment]
What about appeals? They refer to one single file of the folder or the whole folder?

**Comment by turinglabsorg** [comment]
Appeals refers to whole folder, because provider must prove to have all folder, if you have all folder you'll have any single file inside..

If we want to improve granularity we'll need to add a level of complexity, maybe using merkle proofs, but it will complex the contract even more, let's discuss about that.

**Comment by 0xjona** [comment]
Yes and I actually wanted to ask the same question for when you add a string with multiple CIDs, we apply the same consideration for the folder?
Anyway, we should make explicit what users will be able to do for the ALPHA (it means that this issue is closed, set in #35 and eventually we can open a discussion for future improvement) - do I need to open an issue related to CLI of this?

**Comment by turinglabsorg** [comment]
Yes open another issue for cli, then we'll decide if add or not several single cids. On the frontend it can be everything packed as folder in any case so we'll never use it. There's enough flexibility to use it as we want.
