### ISSUE TITLE
Website with signing process for providers and referees

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#16]

**Comment by turinglabsorg** [comment]
- [ ] Add signing logic to Smart Contract
- [ ] Create basic website without GFX
- [ ] Add signing process for both providers and referees
- [ ] Add GFX when it's ready

**Comment by irenegia** [comment]
One question here:
I understand the sign up process for providers (I am a provider in some storage network and I want to boost my service with this extra feature, offering the "retrievability assurance").
We need to create the logic for this and would be very nice to have a website interface for the provider and a website listing all the provides that signed up.
I think this should be thought  as a dynamic procedure: I am a provider, i decide to sign up, after a while I can sign out and then come back... etc  

But, do we want this for referees as well?
Since we have some trust assumption on the set of the referees (eg, be online most of the time, a fraction is honest), I think that the figure of the referee is a static one. The protocol has a fix set of referees, if you want to join of leave, the procedure is more complicate that just a sign up/ sign out (for example, think about the nodes of drand).
So I would propose that referees are a fixed list in the smart contracts implementing the entire protocol and to change referrers you have to deploy a new contract (maybe in a automatic way as suggested in #9 ).

Feedback @nicola and @turinglabsorg ?

**Comment by irenegia** [comment]
also, @turinglabsorg what's the difference between this issue and #4 ?
Thanks!

**Comment by turinglabsorg** [comment]
> also, @turinglabsorg what's the difference between this issue and #4 ? Thanks!

I think there's a duplicate here, @0xjona please close #4 due to duplication, let's talk about registration process here.

**Comment by turinglabsorg** [comment]
> But, do we want this for referees as well?

I think referees should be decided by contract owner (so manually fixed)

>  So I would propose that referees are a fixed list in the smart contracts implementing the entire protocol and to change referrers you have to deploy a new contract (maybe in a automatic way as suggested in https://github.com/protocol/retriev/issues/9 ).

Don't agree should be a fixed list. Think about the simple change i've done (for example) in our pre-alpha contract to change the URL of the provider due to a domain change.. With a new contract would be painful, all current deals would be lost, each provider / referee must operate inside machines to update the contract..

I think it's ok to have the list mutable but only by the owner for referees.

Issue #9 it's intended to allow anyone setup their own consortium, with other rules, timings, tokenomics etc.. @nicola, agree?

**Comment by irenegia** [comment]
@turinglabsorg perfect, I agree with your proposal!
